---

- block:
    - include_tasks: context.yml

    - include_tasks: install.yml

    - include_tasks: configure.yml

  when: want_automounter

- name: set has_automounter
  set_fact:
    has_automounter: "{{ want_automounter }}"
